# Generated by Django 3.1.7 on 2021-02-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210227_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_out_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='book.member'),
        ),
    ]
